apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-redis-certificate
  namespace: cert-manager
spec:
  secretName: test-redis-certs
  dnsNames:
    - cert-test.therednosehomebuyers.com
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
