apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmproxy
  namespace: pcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmproxy
  template:
    metadata:
      labels:
        app: pmproxy
    spec:
      containers:
      - name: pmproxy
        image: ghcr.io/imgproxy/imgproxy:latest
        ports:
        - containerPort: 44322 # Updated to match pmproxy REST API default
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: pcp-config
          mountPath: /etc/pcp
      volumes:
      - name: pcp-config
        configMap:
          name: pcp-config
